name: Reusable Windows Build

on:
  workflow_call:
    inputs:
      prepared_source_artifact_name:
        description: 'The name of the prepared source code artifact to download'
        required: true
        type: string
      win_filename:
        description: 'The final, desired filename for the .zip package'
        required: true
        type: string

jobs:
  build_win:
    runs-on: windows-latest
    steps:
      - name: Download prepared source code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.prepared_source_artifact_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Python dependencies
        run: python -m pip install pyinstaller Pillow numpy scipy platformdirs tqdm

      - name: Build Windows executable
        shell: powershell
        run: |
          python -m PyInstaller --onedir --clean `
            --add-data "msxtileexport.py;." `
            --add-data "msxtilemagic.py;." `
            --add-data "tilerandomizer.py;." `
            --add-data "supertilerandomizer.py;." `
            msxtileforge.py
          cp README.md,LICENSE dist/msxtileforge

      - name: Create final Windows zip archive
        shell: pwsh
        run: Compress-Archive -Path dist/msxtileforge/* -DestinationPath dist/${{ inputs.win_filename }}

      - name: Upload final Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.win_filename }}
          path: dist/${{ inputs.win_filename }}