name: Reusable Linux & Debian Build
on:
  workflow_call:
    inputs:
      prepared_source_artifact_name:
        description: 'The name of the prepared source code artifact to download'
        required: true
        type: string

jobs:
  build_lin:
    runs-on: ubuntu-latest
    steps:
      - name: Download prepared source code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.prepared_source_artifact_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System & Python Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make build-essential fakeroot devscripts dh-python python3-all debhelper-compat=13
          python -m pip install pyinstaller Pillow numpy scipy platformdirs tqdm

      - name: Build Linux Binary and Debian Package
        run: make lin deb

      - name: Upload Linux and Debian artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts # The calling workflow will add the unique suffix
          path: |
            dist/*.tar.gz
            dist/*.deb