  #########################################
  # C. Build Windows package
  #########################################
  build-windows:
    name: Build Windows
    needs: generate-version
    runs-on: windows-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Python dependencies
        run: python -m pip install pyinstaller Pillow numpy scipy platformdirs tqdm

      - name: Update version string in source files
        shell: bash
        run: find . -type f -name "*.py" -exec sed -i "s/<unreleased>/${{ needs.generate-version.outputs.version_string }}/g" {} +

      - name: Build Windows executable
        shell: powershell
        run: |
          python -m PyInstaller --onedir --clean `
            --add-data "msxtileexport.py;." `
            --add-data "msxtilemagic.py;." `
            --add-data "tilerandomizer.py;." `
            --add-data "supertandomizer.py;." `
            msxtileforge.py
          cp README.md,LICENSE dist/msxtileforge

      - name: Create final Windows zip archive
        shell: pwsh
        run: Compress-Archive -Path dist/msxtileforge/* -DestinationPath dist/msxtileforge-windows.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts-${{ github.run_id }}-${{ inputs.branch }}
          path: dist/msxtileforge-windows.zip