# .github/workflows/build-linux.yml

name: Reusable Linux & Debian Build

on:
  workflow_call:
    inputs:
      version_string:
        required: true
        type: string
      artifact_name_linux:
        required: true
        type: string
      artifact_name_deb:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y make build-essential fakeroot devscripts dh-python python3-all debhelper-compat=13 tar zip
          python3 -m pip install pyinstaller Pillow numpy scipy platformdirs tqdm

      - name: Update Version in Files
        run: |
          find . -type f -name "*.py" -exec sed -i "s/<unreleased>/${{ inputs.version_string }}/g" {} +
          DEBIAN_VERSION=$(echo "${{ inputs.version_string }}" | sed -e 's/v//' -e 's/_/~/g')
          sed -i "s/<unreleased>/$DEBIAN_VERSION/g" debian/changelog

      - name: Build Linux .tar.gz package (via Makefile)
        run: make lin

      - name: Build Debian .deb package (via debuild)
        run: debuild -us -uc

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name_linux }}
          path: dist/msxtileforge_linux.tar.gz
          
      - name: Upload Debian Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name_deb }}
          # debuild creates the file in the parent directory
          path: ../*.deb