name: Nightly Build
on:
  schedule:
    # Runs at 4 AM UTC daily.
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ############################################################
  # JOB 1: Find all REL_* branches with recent commits
  ############################################################
  find-active-branches:
    name: Find Active REL Branches
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.get-branches.outputs.branches }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Identify active branches
        id: get-branches
        shell: bash
        run: |
          REMOTE_REL_BRANCHES=$(git branch -r | grep 'origin/REL_' | sed 's/origin\///')
          ACTIVE_BRANCHES=()
          for branch in $REMOTE_REL_BRANCHES; do
            RECENT_COMMIT_COUNT=$(git log "origin/$branch" --since="24 hours ago" --oneline | wc -l)
            if [ "$RECENT_COMMIT_COUNT" -gt 0 ]; then
              ACTIVE_BRANCHES+=("\"$branch\"")
            fi
          done
          JSON_ARRAY=$(IFS=,; echo "[${ACTIVE_BRANCHES[*]}]")
          echo "Found active branches: $JSON_ARRAY"
          echo "branches=${JSON_ARRAY}" >> $GITHUB_OUTPUT

  ############################################################
  # JOB 2: Call the worker workflow for each active branch
  ############################################################
  build:
    name: Build for ${{ matrix.branch }}
    needs: find-active-branches
    if: fromJson(needs.find-active-branches.outputs.branches)[0] != null
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJson(needs.find-active-branches.outputs.branches) }}
    uses: ./.github/workflows/nightly-worker.yml
    with:
      branch: ${{ matrix.branch }}
    secrets: inherit
