name: Nightly Build
on:
  schedule:
    # IMPORTANT: Set this to a time ~10-15 minutes in the future (in UTC) for your test.
    # Example: '0 23 * * *' for 23:00 UTC.
    # After testing, change it to your desired nightly time, e.g., '0 4 * * *' for 4 AM UTC.
    - cron: '15 11 * * *'
  # Allow manual trigger for easier debugging
  workflow_dispatch:

permissions:
  contents: write # Needed to post commit comments

jobs:
  ############################################################
  # JOB 1: Find all REL_* branches with recent commits
  ############################################################
  find-active-branches:
    name: Find Active REL Branches
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.get-branches.outputs.branches }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to get commit history

      - name: Identify active branches
        id: get-branches
        shell: bash
        run: |
          echo "Searching for REL_* branches with commits in the last 24 hours..."
          
          # Get a list of all remote REL branches
          REMOTE_REL_BRANCHES=$(git branch -r | grep 'origin/REL_' | sed 's/origin\///')
          
          ACTIVE_BRANCHES=()
          for branch in $REMOTE_REL_BRANCHES; do
            echo "Checking branch: $branch"
            
            # Check if there's at least one commit on this branch in the last day
            # We use --git-dir to avoid issues with sparse checkouts
            RECENT_COMMIT_COUNT=$(git --git-dir=$PWD/.git log "origin/$branch" --since="24 hours ago" --oneline | wc -l)

            if [ "$RECENT_COMMIT_COUNT" -gt 0 ]; then
              echo " -> Found $RECENT_COMMIT_COUNT recent commit(s). Adding to build list."
              # Add the branch name in quotes to the bash array
              ACTIVE_BRANCHES+=("\"$branch\"")
            else
              echo " -> No recent commits. Skipping."
            fi
          done

          if [ ${#ACTIVE_BRANCHES[@]} -eq 0 ]; then
            echo "No active REL branches found."
            echo "branches=[]" >> $GITHUB_OUTPUT
          else
            # Convert the bash array to a comma-separated string, then wrap in JSON brackets
            JSON_ARRAY=$(IFS=,; echo "[${ACTIVE_BRANCHES[*]}]")
            echo "Found active branches: $JSON_ARRAY"
            echo "branches=${JSON_ARRAY}" >> $GITHUB_OUTPUT
          fi

  ############################################################
  # JOB 2: Build, upload, and comment for each active branch
  ############################################################
  build-and-release-nightly:
    name: Build Nightly for ${{ matrix.branch }}
    needs: find-active-branches
    if: fromJson(needs.find-active-branches.outputs.branches)[0] != null
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJson(needs.find-active-branches.outputs.branches) }}
    steps:
      - name: Checkout specific branch (${{ matrix.branch }})
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System & Python Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make build-essential fakeroot devscripts dh-python python3-all debhelper-compat=13 curl
          python -m pip install --upgrade pip
          python -m pip install pyinstaller Pillow numpy scipy platformdirs tqdm

      - name: Construct Nightly Version String and IA Identifier
        id: versioning
        shell: bash
        run: |
          BASE_VERSION=$(echo "${{ matrix.branch }}" | sed 's/REL_//')
          DATE_STAMP=$(date +'%Y%m%d')
          GLOBAL_RUN_NUM="${{ github.run_number }}"
          FINAL_VERSION="${BASE_VERSION}_nightly${DATE_STAMP}_${GLOBAL_RUN_NUM}"
          echo "VERSION_STRING=${FINAL_VERSION}" >> $GITHUB_OUTPUT
          
          DEBIAN_VERSION=$(echo "$FINAL_VERSION" | sed -e 's/_/~/g')
          echo "DEBIAN_VERSION=${DEBIAN_VERSION}" >> $GITHUB_OUTPUT
          
          IA_IDENTIFIER="msxtileforge-nightly-${DATE_STAMP}"
          echo "IA_IDENTIFIER=${IA_IDENTIFIER}" >> $GITHUB_OUTPUT

      - name: Update Version in Files
        run: |
          find . -type f -name "*.py" -exec sed -i "s/<unreleased>/${{ steps.versioning.outputs.VERSION_STRING }}/g" {} +
          sed -i "s/<unreleased>/${{ steps.versioning.outputs.DEBIAN_VERSION }}/g" debian/changelog

      - name: Build Linux Binary and Debian Package
        run: make lin deb
        
      - name: Upload to Internet Archive and Create Comment
        id: uploader
        env:
          IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }} # Using only S3 keys now
          IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}
          IA_IDENTIFIER: ${{ steps.versioning.outputs.IA_IDENTIFIER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          # --- 1. Find the Build Artifacts ---
          TAR_FILE=$(find dist -name "*.tar.gz")
          DEB_FILE=$(find dist -name "*.deb")
          TAR_FILENAME=$(basename "$TAR_FILE")
          DEB_FILENAME=$(basename "$DEB_FILE")
          ITEM_TITLE="MSX Tile Forge Nightly Build (${{ steps.versioning.outputs.VERSION_STRING }})"

          # --- 2. Create Item and Upload First File with All Metadata ---
          echo "Creating Item '${IA_IDENTIFIER}' and uploading $TAR_FILENAME..."
          curl --fail --location --request PUT \
            --header "Authorization: LOW ${IA_ACCESS_KEY}:${IA_SECRET_KEY}" \
            --header "x-amz-auto-make-bucket: 1" \
            --header "x-archive-meta-title: ${ITEM_TITLE}" \
            --header "x-archive-meta-collection: opensource_media" \
            --header "x-archive-meta-mediatype: software" \
            --header "x-archive-meta01-subject: msxtileforge_nightly_build" \
            --header "x-archive-meta02-subject: msxtileforge" \
            --upload-file "$TAR_FILE" \
            "https://s3.us.archive.org/${IA_IDENTIFIER}/${TAR_FILENAME}"

          # --- 3. Upload Second File to the Same Item ---
          echo "Uploading $DEB_FILENAME to item '${IA_IDENTIFIER}'..."
          sleep 15
          curl --fail --location --request PUT \
            --header "Authorization: LOW ${IA_ACCESS_KEY}:${IA_SECRET_KEY}" \
            --upload-file "$DEB_FILE" \
            "https://s3.us.archive.org/${IA_IDENTIFIER}/${DEB_FILENAME}"

          # --- 4. Construct URLs and Post Comment ---
          echo "Uploads complete. Waiting for processing..."
          sleep 30
          BASE_URL="https://archive.org/download/$IA_IDENTIFIER"
          TAR_URL="$BASE_URL/$TAR_FILENAME"
          DEB_URL="$BASE_URL/$DEB_FILENAME"

          echo "::notice::Item URL: https://archive.org/details/$IA_IDENTIFIER"
          
          COMMIT_SHA=$(git rev-parse HEAD)
          COMMENT_BODY="🚀 **Nightly Build Successful for \`${{ matrix.branch }}\`**

          A new historical archive for this build has been created and tagged for collection.
          **Item Page:** [${IA_IDENTIFIER}](https://archive.org/details/${IA_IDENTIFIER})

          Version: \`${{ steps.versioning.outputs.VERSION_STRING }}\`
          Commit: \`$COMMIT_SHA\`

          **Direct Downloads:**
          *   **Linux (tar.gz):** [$TAR_FILENAME]($TAR_URL)
          *   **Debian (.deb):** [$DEB_FILENAME]($DEB_URL)"

          echo "Posting comment to commit $COMMIT_SHA"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/commits/$COMMIT_SHA/comments \
            -f body="$COMMENT_BODY"


