name: Reusable Nightly Worker

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      IA_ACCESS_KEY:
        required: true
      IA_SECRET_KEY:
        required: true

jobs:
  #########################################
  # A. Generate version strings and filenames
  #########################################
  generate-version:
    name: Generate Version & Filenames
    runs-on: ubuntu-latest
    outputs:
      version_string: ${{ steps.versioning.outputs.VERSION_STRING }}
      debian_version: ${{ steps.versioning.outputs.DEBIAN_VERSION }}
      item_identifier: ${{ steps.versioning.outputs.ITEM_IDENTIFIER }}
      prepared_source_artifact_name: ${{ steps.versioning.outputs.PREPARED_SOURCE_ARTIFACT_NAME }}
      win_filename: ${{ steps.versioning.outputs.WIN_FILENAME }}
      lin_filename: ${{ steps.versioning.outputs.LIN_FILENAME }}
      deb_filename: ${{ steps.versioning.outputs.DEB_FILENAME }}
      src_filename: ${{ steps.versioning.outputs.SRC_FILENAME }}
    steps:
      - name: Construct Nightly Version Strings and Filenames
        id: versioning
        shell: bash
        run: |
          BASE_VERSION=$(echo "${{ inputs.branch }}" | sed 's/REL_//')
          DATE_STAMP=$(date +'%y%m%d')
          GLOBAL_RUN_NUM="${{ github.run_number }}"
          
          FINAL_VERSION="${BASE_VERSION}_nightly${DATE_STAMP}_${GLOBAL_RUN_NUM}"
          BASE_NAME="msxtileforge_${FINAL_VERSION}"
          ITEM_IDENTIFIER="${BASE_NAME}_all"

          echo "VERSION_STRING=${FINAL_VERSION}" >> $GITHUB_OUTPUT
          echo "DEBIAN_VERSION=$(echo "$FINAL_VERSION" | sed -e 's/_/~/g')" >> $GITHUB_OUTPUT
          echo "ITEM_IDENTIFIER=${ITEM_IDENTIFIER}" >> $GITHUB_OUTPUT
          echo "PREPARED_SOURCE_ARTIFACT_NAME=prepared-source-${{ github.run_id }}-${{ inputs.branch }}" >> $GITHUB_OUTPUT
          echo "WIN_FILENAME=${BASE_NAME}_win.zip" >> $GITHUB_OUTPUT
          echo "LIN_FILENAME=${BASE_NAME}_lin.tar.gz" >> $GITHUB_OUTPUT
          echo "DEB_FILENAME=${BASE_NAME}_deb.deb" >> $GITHUB_OUTPUT
          echo "SRC_FILENAME=${BASE_NAME}_src.zip" >> $GITHUB_OUTPUT

  #########################################
  # B. Prepare source code
  #########################################
  prepare-source:
    name: Prepare Source Code
    needs: generate-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Update version strings using reusable action
        uses: ./.github/actions/update-version-in-files
        with:
          version_string: ${{ needs.generate-version.outputs.version_string }}
          debian_version: ${{ needs.generate-version.outputs.debian_version }}

      - name: Upload prepared source as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.generate-version.outputs.prepared_source_artifact_name }}
          path: .

  #########################################
  # C. Call the Reusable Builders
  #########################################
  build-linux:
    name: Call Linux Builder
    needs: [generate-version, prepare-source]
    uses: ./.github/workflows/build-linux.yml
    with:
      prepared_source_artifact_name: ${{ needs.generate-version.outputs.prepared_source_artifact_name }}
      lin_filename: ${{ needs.generate-version.outputs.lin_filename }}
      deb_filename: ${{ needs.generate-version.outputs.deb_filename }}

  build-windows:
    name: Call Windows Builder
    needs: [generate-version, prepare-source]
    uses: ./.github/workflows/build-windows.yml
    with:
      prepared_source_artifact_name: ${{ needs.generate-version.outputs.prepared_source_artifact_name }}
      win_filename: ${{ needs.generate-version.outputs.win_filename }}

  build-source:
    name: Call Source Builder
    needs: [generate-version, prepare-source]
    uses: ./.github/workflows/build-source.yml
    with:
      prepared_source_artifact_name: ${{ needs.generate-version.outputs.prepared_source_artifact_name }}
      src_filename: ${{ needs.generate-version.outputs.src_filename }}

  #########################################
  # D. Publish all artifacts to Internet Archive
  #########################################
  publish:
    name: Publish to Internet Archive
    needs: [generate-version, build-linux, build-windows, build-source]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Download all final build artifacts
        uses: actions/download-artifact@v4
        with:
          path: final-packages

      - name: Package and Rename Files
        id: package
        uses: ./.github/actions/package-and-rename-artifacts
        with:
          base_name: ${{ needs.generate-version.outputs.base_name }}

      - name: Upload Packages to Internet Archive
        id: upload-packages
        env:
          IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }}
          IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}
          IA_IDENTIFIER: ${{ needs.generate-version.outputs.item_identifier }}
        shell: bash
        run: |
          ITEM_TITLE="MSX Tile Forge Nightly Build (${{ needs.generate-version.outputs.version_string }})"
          PACKAGE_PATH="${{ steps.package.outputs.package_path }}"
          
          cd "${PACKAGE_PATH}"
          UPLOAD_COUNT=0
          COMMENT_FILE_LIST=""
          
          for FILE in *; do
            echo "Uploading $FILE to item '${IA_IDENTIFIER}'..."
            if [ $UPLOAD_COUNT -eq 0 ]; then
              # The first file creates the item and sets all metadata
              curl --fail --location --request PUT \
                --header "Authorization: LOW ${IA_ACCESS_KEY}:${IA_SECRET_KEY}" \
                --header "x-amz-auto-make-bucket: 1" \
                --header "x-archive-meta-title: ${ITEM_TITLE}" \
                --header "x-archive-meta-collection: opensource_media" \
                --header "x-archive-meta-mediatype: software" \
                --header "x-archive-meta01-subject: msxtileforge_nightly_build" \
                --header "x-archive-meta02-subject: msxtileforge" \
                --upload-file "$FILE" \
                "https://s3.us.archive.org/${IA_IDENTIFIER}/${FILE}"
            else
              # Subsequent files are just added to the now-existing item
              sleep 15
              curl --fail --location --request PUT \
                --header "Authorization: LOW ${IA_ACCESS_KEY}:${IA_SECRET_KEY}" \
                --upload-file "$FILE" \
                "https://s3.us.archive.org/${IA_IDENTIFIER}/${FILE}"
            fi
            UPLOAD_COUNT=$((UPLOAD_COUNT + 1))
            
            # Build the markdown list for the commit comment
            FILE_URL="https://archive.org/download/${IA_IDENTIFIER}/${FILE}"
            COMMENT_FILE_LIST="${COMMENT_FILE_LIST}*   **${FILE}**: [Download](${FILE_URL})\n"
          done
          
          # Use a heredoc to pass the multiline string to the output
          echo "comment_file_list<<EOF" >> $GITHUB_OUTPUT
          echo -e "${COMMENT_FILE_LIST}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Upload Item Icon
        env:
          IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }}
          IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}
          IA_IDENTIFIER: ${{ needs.generate-version.outputs.item_identifier }}
        run: |
          echo "Uploading item icon..."
          curl --fail --location --request PUT \
            --header "Authorization: LOW ${IA_ACCESS_KEY}:${IA_SECRET_KEY}" \
            --header "x-archive-meta-thumbnail: 1" \
            --upload-file "./Resources/splash4_1.png" \
            "https://s3.us.archive.org/${IA_IDENTIFIER}/icon.png"

      - name: Post Final Commit Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          COMMENT_BODY="🚀 **Nightly Build Successful for \`${{ inputs.branch }}\`**

          A new historical archive for this build has been created and tagged for collection.
          **Item Page:** [${{ needs.generate-version.outputs.item_identifier }}](https://archive.org/details/${{ needs.generate-version.outputs.item_identifier }})

          Version: \`${{ needs.generate-version.outputs.version_string }}\`
          Commit: \`${COMMIT_SHA}\`

          **Downloads:**
          ${{ steps.upload-packages.outputs.comment_file_list }}"

          echo "Posting comment to commit ${COMMIT_SHA}"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/commits/${COMMIT_SHA}/comments \
            -f body=- <<EOF
          ${COMMENT_BODY}
          EOF

