# .github/workflows/release.yml

name: MSX Tile Forge Build Orchestrator

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of build to run'
        required: true
        default: 'dev_build'
        type: choice
        options: [dev_build] # Add other types like 'rc_build' back in later

jobs:
  ############################################################
  # JOB 1: Calculate Version and Trigger Worker Workflows
  ############################################################
  call_builds:
    name: Calculate Version & Call Builds
    runs-on: ubuntu-latest
    outputs:
      version_string: ${{ steps.versioning.outputs.VERSION_STRING }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Construct Dev Version String
        id: versioning
        shell: bash
        run: |
          echo "--- Start Version Construction ---"
          # Use github.ref which contains the full path, e.g., refs/heads/REL_.../TKT_...
          FULL_REF="${{ github.ref }}"
          echo "1. Full Git Ref (github.ref): $FULL_REF"
          
          # This robustly extracts the version by finding what's between "REL_" and "/TKT_"
          BASE_VERSION=$(echo "$FULL_REF" | sed -n 's/.*REL_\([0-9.]*\)\/TKT_.*/\1/p')
          echo "2. Parsed BASE_VERSION: $BASE_VERSION"
          
          # This robustly extracts the ticket number from the full ref
          TICKET_NUM=$(echo "$FULL_REF" | grep -oP 'TKT_[0-9]+' | sed 's/TKT_//')
          echo "3. Parsed TICKET_NUM: $TICKET_NUM"
          
          BRANCH_BUILD_NUM=$(git rev-list --count HEAD)
          echo "4. Parsed BRANCH_BUILD_NUM (Commit Count): $BRANCH_BUILD_NUM"
          
          GLOBAL_BUILD_NUM="${{ github.run_number }}"
          echo "5. Parsed GLOBAL_BUILD_NUM (Run Number): $GLOBAL_BUILD_NUM"
          
          FINAL_VERSION="v${BASE_VERSION}_dev${TICKET_NUM}.${BRANCH_BUILD_NUM}_${GLOBAL_BUILD_NUM}"
          echo "6. Assembled FINAL_VERSION: $FINAL_VERSION"
          echo "--- End Version Construction ---"
          
          echo "VERSION_STRING=${FINAL_VERSION}" >> $GITHUB_OUTPUT

  ############################################################
  # JOB 2: Run the actual builds by calling the reusable workflows
  ############################################################
  build_binaries:
    name: Build Binaries
    needs: call_builds
    uses: ./.github/workflows/build-windows.yml
    with:
      version_string: ${{ needs.call_builds.outputs.version_string }}
      
  build_linux_binaries:
    name: Build Linux Binaries
    needs: call_builds
    uses: ./.github/workflows/build-linux.yml
    with:
      version_string: ${{ needs.call_builds.outputs.version_string }}
